//! Router generator

use crate::ast::{Declaration, Program};
use crate::analyzer::SymbolTable;
use crate::GeneratedFile;

/// Generate router.ts
pub fn generate(program: &Program, _symbols: &SymbolTable) -> GeneratedFile {
    let mut output = String::new();

    // Header
    output.push_str("// Generated by HTMS Compiler\n");
    output.push_str("// Do not edit manually\n\n");

    // Inline Router class
    output.push_str("interface RouterConfig {\n");
    output.push_str("  mode: 'hash' | 'history';\n");
    output.push_str("  routes: Record<string, () => void>;\n");
    output.push_str("  notFound: () => void;\n");
    output.push_str("}\n\n");
    output.push_str("class Router {\n");
    output.push_str("  constructor(config: RouterConfig) {\n");
    output.push_str("    const handleRoute = () => {\n");
    output.push_str("      const hash = window.location.hash.slice(1) || '/';\n");
    output.push_str("      const handler = config.routes[hash];\n");
    output.push_str("      if (handler) {\n");
    output.push_str("        handler();\n");
    output.push_str("      } else {\n");
    output.push_str("        config.notFound();\n");
    output.push_str("      }\n");
    output.push_str("    };\n");
    output.push_str("    window.addEventListener('hashchange', handleRoute);\n");
    output.push_str("    handleRoute();\n");
    output.push_str("  }\n");
    output.push_str("}\n\n");

    // Collect page imports
    let pages: Vec<(&str, &str)> = program.body.iter()
        .filter_map(|decl| {
            if let Declaration::Page(p) = decl {
                Some((p.name.as_str(), p.route.as_str()))
            } else {
                None
            }
        })
        .collect();

    // Import page functions
    let page_names: Vec<String> = pages.iter()
        .map(|(name, _)| format!("{}Page", capitalize(name)))
        .collect();

    if !page_names.is_empty() {
        output.push_str(&format!(
            "import {{ {} }} from './templates';\n",
            page_names.join(", ")
        ));
    }

    output.push_str("\n");

    // Context
    output.push_str("// Application context\n");
    output.push_str("let context: Record<string, unknown> = {};\n");
    output.push_str("let currentPage: string = '';\n");
    output.push_str("const appContainer = document.getElementById('app');\n\n");

    // Context functions
    output.push_str("export function getContext(): Record<string, unknown> {\n");
    output.push_str("  return context;\n");
    output.push_str("}\n\n");

    output.push_str("export function setContext(data: Record<string, unknown>): void {\n");
    output.push_str("  context = data;\n");
    output.push_str("}\n\n");

    output.push_str("export function rerender(): void {\n");
    output.push_str("  if (currentPage && appContainer) {\n");
    output.push_str("    const renderer = routes[currentPage];\n");
    output.push_str("    if (renderer) {\n");
    output.push_str("      appContainer.innerHTML = '';\n");
    output.push_str("      appContainer.appendChild(renderer(context));\n");
    output.push_str("    }\n");
    output.push_str("  }\n");
    output.push_str("}\n\n");

    // Routes object
    output.push_str("// Route definitions\n");
    output.push_str("const routes: Record<string, (ctx: Record<string, unknown>) => HTMLElement> = {\n");

    for (name, route) in &pages {
        output.push_str(&format!(
            "  '{}': {}Page,\n",
            route,
            capitalize(name)
        ));
    }

    output.push_str("};\n\n");

    // Render function
    output.push_str("function renderPage(route: string): void {\n");
    output.push_str("  currentPage = route;\n");
    output.push_str("  const renderer = routes[route];\n");
    output.push_str("  if (renderer && appContainer) {\n");
    output.push_str("    appContainer.innerHTML = '';\n");
    output.push_str("    appContainer.appendChild(renderer(context));\n");
    output.push_str("  } else if (appContainer) {\n");
    output.push_str("    const el = document.createElement('h1');\n");
    output.push_str("    el.textContent = '404 - Page Not Found';\n");
    output.push_str("    appContainer.innerHTML = '';\n");
    output.push_str("    appContainer.appendChild(el);\n");
    output.push_str("  }\n");
    output.push_str("}\n\n");

    // Router instance
    output.push_str("// Create router\n");
    output.push_str("export const router = new Router({\n");
    output.push_str("  mode: 'hash',\n");
    output.push_str("  routes: {\n");

    for (_, route) in &pages {
        output.push_str(&format!(
            "    '{}': () => renderPage('{}'),\n",
            route, route
        ));
    }

    output.push_str("  },\n");
    output.push_str("  notFound: () => renderPage('__404__'),\n");
    output.push_str("});\n");

    GeneratedFile {
        path: "router.ts".to_string(),
        content: output,
    }
}

fn capitalize(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
    }
}
