// Generated by HTMS Compiler
// Do not edit manually

import { getContext, setContext, rerender } from './router';
import { actions } from './actions';

export interface ActionContext {
  data: Record<string, unknown>;
  rerender: () => void;
}

export function initEvents(): void {
  // Event delegation
  document.addEventListener('click', handleEvent);
  document.addEventListener('submit', handleEvent);
  document.addEventListener('input', handleEvent);
  document.addEventListener('change', handleEvent);
  document.addEventListener('blur', handleEvent, true);
  document.addEventListener('focus', handleEvent, true);

  // Two-way binding
  initBinding();
}

function handleEvent(event: Event): void {
  const target = event.target as HTMLElement;
  const actionEl = target.closest('[data-action]') as HTMLElement;

  if (!actionEl) return;

  const actionName = actionEl.dataset.action;
  const eventType = actionEl.dataset.event;

  // Only handle if event type matches
  if (eventType && eventType !== event.type) return;

  // Handle modifiers
  if (actionEl.dataset.prevent === 'true') {
    event.preventDefault();
  }
  if (actionEl.dataset.stop === 'true') {
    event.stopPropagation();
  }

  // Get action
  const action = (actions as Record<string, Function>)[actionName!];
  if (action) {
    const ctx: ActionContext = {
      data: getContext(),
      rerender: () => {
        setContext(ctx.data);
        rerender();
      }
    };

    // Parse arguments if present
    const argsStr = actionEl.dataset.args;
    if (argsStr) {
      try {
        const args = JSON.parse(argsStr);
        action(...args)(ctx, event);
      } catch {
        action(ctx, event);
      }
    } else {
      action(ctx, event);
    }

    // Handle once modifier
    if (actionEl.dataset.once === 'true') {
      actionEl.removeAttribute('data-action');
    }
  }
}

function initBinding(): void {
  document.addEventListener('input', (e) => {
    const el = e.target as HTMLInputElement;
    const bindPath = el.dataset.bind;
    if (bindPath) {
      const ctx = getContext();
      setNestedValue(ctx, bindPath, el.value);
      setContext(ctx);
    }
  });

  document.addEventListener('change', (e) => {
    const el = e.target as HTMLInputElement;
    const bindPath = el.dataset.bind;
    if (bindPath && el.type === 'checkbox') {
      const ctx = getContext();
      setNestedValue(ctx, bindPath, el.checked);
      setContext(ctx);
    }
  });
}

function setNestedValue(obj: Record<string, unknown>, path: string, value: unknown): void {
  const keys = path.split('.');
  const last = keys.pop()!;
  const target = keys.reduce((o, k) => {
    if (!(o as Record<string, unknown>)[k]) {
      (o as Record<string, unknown>)[k] = {};
    }
    return (o as Record<string, unknown>)[k];
  }, obj) as Record<string, unknown>;
  target[last] = value;
}
