// Generated by HTMS Compiler
// Do not edit manually

import { Router } from './runtime';
import { HomePage, AboutPage } from './templates';

// Application context
let context: Record<string, unknown> = {};
let currentPage: string = '';
const appContainer = document.getElementById('app');

export function getContext(): Record<string, unknown> {
  return context;
}

export function setContext(data: Record<string, unknown>): void {
  context = data;
}

export function rerender(): void {
  if (currentPage && appContainer) {
    const renderer = routes[currentPage];
    if (renderer) {
      appContainer.innerHTML = '';
      appContainer.appendChild(renderer(context));
    }
  }
}

// Route definitions
const routes: Record<string, (ctx: Record<string, unknown>) => HTMLElement> = {
  '/': HomePage,
  '/about': AboutPage,
};

function renderPage(route: string): void {
  currentPage = route;
  const renderer = routes[route];
  if (renderer && appContainer) {
    appContainer.innerHTML = '';
    appContainer.appendChild(renderer(context));
  } else if (appContainer) {
    const el = document.createElement('h1');
    el.textContent = '404 - Page Not Found';
    appContainer.innerHTML = '';
    appContainer.appendChild(el);
  }
}

// Create router
export const router = new Router({
  mode: 'hash',
  routes: {
    '/': () => renderPage('/'),
    '/about': () => renderPage('/about'),
  },
  notFound: () => renderPage('__404__'),
});
