// Generated by HTMS Compiler
// Do not edit manually

import { actions } from './actions';

export type Context = Record<string, unknown>;

export function NavBar(ctx: Context): HTMLElement {
  const el0 = document.createElement('nav');
  el0.className = 'navbar';
  const el1 = document.createElement('a');
  el1.href = '#/';
  const el2 = document.createTextNode('Home');
  el1.appendChild(el2);
  el0.appendChild(el1);
  const el3 = document.createElement('a');
  el3.href = '#/about';
  const el4 = document.createTextNode('About');
  el3.appendChild(el4);
  el0.appendChild(el3);
  return el0;
}

export function HomePage(ctx: Context): HTMLElement {
  const fragment = document.createDocumentFragment();
  const el0 = NavBar(ctx);
  fragment.appendChild(el0);
  const el1 = document.createElement('div');
  el1.className = 'hero';
  const el2 = document.createElement('h1');
  const el3 = document.createTextNode('Welcome to HTMS!');
  el2.appendChild(el3);
  el1.appendChild(el2);
  fragment.appendChild(el1);
  const root = document.createElement('div');
  root.appendChild(fragment);
  return root;
}

export function AboutPage(ctx: Context): HTMLElement {
  const fragment = document.createDocumentFragment();
  const el0 = NavBar(ctx);
  fragment.appendChild(el0);
  const el1 = document.createElement('div');
  const el2 = document.createTextNode('About Page');
  el1.appendChild(el2);
  fragment.appendChild(el1);
  const root = document.createElement('div');
  root.appendChild(fragment);
  return root;
}

